[custom]

;设置规则标志位
ruleset=Adobe,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/Adobe.list
ruleset=Apple,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/Apple.list
ruleset=Bing,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/Bing.list
ruleset=JetBrains,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/JetBrains.list
ruleset=Microsoft,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/Microsoft.list
ruleset=❤️ 纯爱鸡米,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🚀 手动切换`select`[]♻️ 自动选择`.*
custom_proxy_group=Adobe`select`[]DIRECT`[]🚀 手动切换
custom_proxy_group=Apple`select`[]DIRECT`[]🚀 手动切换
custom_proxy_group=Bing`select`[]DIRECT`[]🚀 手动切换
custom_proxy_group=JetBrains`select`[]DIRECT`[]🚀 手动切换
custom_proxy_group=Microsoft`select`[]DIRECT`[]🚀 手动切换
custom_proxy_group=❤️ 纯爱鸡米`select`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 手动切换`[]DIRECT
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true
